# KillStreak by Jack Wilsdon (jackwilsdon)
KillStreak:
  updater-enabled: true
  reset-on-disconnect: false
  streaks:
    5:
      potion: SPEED
      level: 1
    10:
      potion: SPEED
      level: 2
  messages:
    broadcast-on-powerup: true
    message-tag: '&f[&aKillStreak&f] '
    killstreak-color: '&c'
    username-color: '&e'
PlayerStreaks: