name: ${project.name}
version: ${project.version}
description: ${project.description}
author: "Jack Wilsdon (jackwilsdon)"
website: ${project.url}
main: me.jackwilsdon.killstreak.KillStreakPlugin

commands:
    killstreak:
        description: View your current kill streak
        usage: /killstreak
        aliases: ["ks"]
